// GENERATED by build-linux.sh — do not edit by hand.
// Regenerated on every build; see build-linux.sh for why this is a generated
// file rather than a runtime lookup.

public enum BuildInfo {
    /// Short git commit of the source this binary was built from, with a
    /// "-dirty" suffix if the working tree had uncommitted changes.
    public static let gitCommit = "99b0079"

    /// UTC timestamp of the build, ISO 8601.
    public static let buildTimestampUTC = "2026-08-25T07:28:21Z"

    /// SHA-256 of the linked binary — written to build_info.json post-link,
    /// since the binary cannot contain its own hash.
    public static let binarySHA256 = "pending"
}
