// BuildInfo.swift
//
// Build-time provenance constants, injected by build-linux.sh (and by
// `swift build` via the same generator for local Mac builds).
//
// WHY A GENERATED FILE rather than reading git/sha at runtime:
//
// Both values would otherwise require spawning a subprocess — `git rev-parse
// HEAD` and `shasum` — which this project deliberately avoids everywhere it
// can. The precedent is ResourceUsage.swift: sched_getaffinity failed to
// resolve under the Debian Trixie SDK's Glibc modulemap, and the fix was to
// drop the C interop entirely rather than add a shim. Process spawning carries
// the same class of risk: a Linux-only dependency, a macOS failure path, and
// something that can break on a toolchain change, all in service of metadata.
//
// It is also simply more accurate. A binary computing its own SHA at runtime
// has to locate its own executable path, which is awkward and platform-
// specific. The SHA the build script just computed over the artefact it just
// produced is exact by construction.
//
// This file is CHECKED IN with "unknown" placeholders so the package always
// builds. build-linux.sh overwrites it immediately before compiling, and a
// build from a dirty or non-git tree still succeeds — it just records
// "unknown", which is honest rather than fabricated.
//
// Regeneration snippet for build-linux.sh (write BEFORE `swift build`):
//
//   COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
//   DIRTY=$(git diff --quiet 2>/dev/null || echo "-dirty")
//   cat > Sources/RADFLCore/Telemetry/BuildInfo.swift <<EOF
//   // GENERATED by build-linux.sh — do not edit by hand.
//   public enum BuildInfo {
//       public static let gitCommit = "${COMMIT}${DIRTY}"
//       public static let buildTimestampUTC = "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
//       public static let binarySHA256 = "pending"
//   }
//   EOF
//
// binarySHA256 stays "pending" at compile time for the obvious reason — the
// binary does not exist yet. build-linux.sh should compute it AFTER linking
// and write it into a sibling `build_info.json` next to the binary; the
// collection script picks it up from there. Recording a SHA the binary cannot
// know about itself is preferable to embedding a wrong one.

public enum BuildInfo {
    /// Short git commit of the source this binary was built from, with a
    /// "-dirty" suffix if the working tree had uncommitted changes.
    /// "unknown" when built outside a git tree.
    public static let gitCommit = "unknown"

    /// UTC timestamp of the build, ISO 8601.
    public static let buildTimestampUTC = "unknown"

    /// SHA-256 of the linked binary. "pending" in the checked-in version —
    /// see the file header for why this is written to build_info.json
    /// post-link rather than embedded.
    public static let binarySHA256 = "pending"
}
